# @package _global_.model.scaler
_target_: src.models.components.scalers.standardizing_scaler.StandardizingScaler
lattice_repr: ${model.lattice_repr}
center_cart_coords: ${model.center_cart_coords}
datasets:
  - data_dir: ${data.data_dir}
    dataset_name: ${data.dataset_name}
